version: 0.0
os: linux
files:
  - source: /html/
    destination: /usr/share/nginx/html/
    overwrite: true
hooks:
  BeforeInstall:
     - location: /scripts/install
       timeout: 300
       runas: root
     - location: /scripts/start_server
       timeout: 300
       runas: root
  ApplicationStop:
     - location: /scripts/stop_server
       timeout: 300
       runas: root
